apiVersion: v1
entries:
  camel-dashboard-console:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-09-19T11:26:54.300667707Z"
    description: A Helm chart for installing the Camel Dashboard OpenShift Console
      plugin
    digest: f6ce5436261155c9815ca9bac425fb1c7601213da0755c3810f6352e74ed910d
    keywords:
    - camel
    - dashboard
    - console
    - react
    name: camel-dashboard-console
    sources:
    - https://github.com/camel-tooling/camel-dashboard-console.git
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-dashboard-console-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-19T11:26:54.300162698Z"
